### ISSUE TITLE
make genkeys.py executable / check for existence of current/signing_key.pem

### ISSUE THREAD

**Issue by itoffshore** [gene-git/Arch-SKM#2]
Hi Gene,

* `certs-local/genkeys.py` needs to be made executable

* `genkeys.py` at line `289` should check `current/signing_key.pem` exists before querying it's `mtime` (it will always not exist on a new kernel build  / anytime a kernel is built with `makepkg`):

https://github.com/gene-git/Arch-SKM/blob/3500ca8a3354dd42a2d95f3590869cb34b1f8d2d/certs-local/genkeys.py#L289

or perhaps the check is better in `main()` for readability - don't run `check_refresh()` if the file doesn't exist

**Comment by gene-git** [comment]
good catch - thanks. 
1. Fixed the file exists check.
2. can't find a way using github gui to make executable - I did manual upload as in past I had some problem with git push from my local repo - I should re-investigate. 
Thank you!

**Comment by gene-git** [comment]
In my little brain - non existence of key file implies a refresh - so I prefer to keep logic in one place. If that makes sense

**Comment by gene-git** [comment]
did a git push from my local repo - hopefully that sorts out any executable bits.
