### ISSUE TITLE
check for kernel config for other arches

### ISSUE THREAD

**Issue by itoffshore** [gene-git/Arch-SKM#3]
Hi Gene,

The fix for `check_refresh()` seems ok - `linux-hardened` is buidiing under the new setup.

When I added functionality for building AUR kernels I noticed some kernels which supported other arches had a `config.amd64` symlink. I worked around this in the [`PKGBUILD` example](https://github.com/itoffshore/Arch-SKM/blob/4c2de490b3870f11bb2097095fe77a3b1e40bd76/Arch-Linux-PKGBUILD-example#L50) with:
```
# some AUR kernels support 64bit / 32bit / armv7h
local arch=$(lscpu | grep ^Architecture | awk '{print $2}')
local config_file=$(find ../src -maxdepth 1 \
   -regextype posix-extended -regex ".*config(.$arch)?")
```
Now that `fix_config.sh` is no longer used could this functionality be used in `genkeys.py` ? (which at the moment assumes a `config` symlink always exists)

https://github.com/gene-git/Arch-SKM/blob/35b7e89fdd10c62ea9024481c15b2149e131b0fc/certs-local/genkeys.py#L52

**Comment by gene-git** [comment]
Can you use the --config <config-file> option of genkeys.py ?

**Comment by gene-git** [comment]
you can run genkeys on each config and it will use same key (provided refresh time not too short)

**Comment by gene-git** [comment]
Since the choice of config file name is specific to the PKGBUILD , and in principle arbitrary,  i wonder if those could use a variable with a  list of all the config files - and then use that  variable in prepare() to run genkeys on each of them.

You've highlighted that genkeys should probably always be called with --config and perhaps not rely on a default name.

Would that work okay for you?

**Comment by gene-git** [comment]
Running multiples assumes that all configs use same key type ( EC or RSA ) and not some of one and some of the other. hopefully that's ok in practice. To be more defensive I could use separate directories for different key types.  I'll think about how that might work.

**Comment by itoffshore** [comment]
Yes just don't rely on a default name - when I poked around in the various AUR kernel `PKGBUILD` previously, the `config` was just optionally something like `config.x86_64` (but only for kernels that were not 64 bit only)

I don't think it needs to be complicated - just a python file search in the top level directory for a file beginning with `config`

I can update my `PKGBUILD` example with always using a `--config` option & see how it goes.

---

the only other issue I've found is the packaging example step just before the `rsync` - I think because now `current_key_dir` is no longer created (it was used in the old shell scripts) :

```
msg2 "Local Signing certs for out-of-tree modules..."

# now only 1 level up as certs-local exists at the same dir level as 'config' to work with genkeys.py
##  certs_local_src="../../certs-local"
certs_local_src="../certs-local"
key_dir=$(<${certs_local_src}/current_key_dir)

certs_local_dst="${builddir}/certs-local"
signer="sign_manual.sh"
mkdir -p ${certs_local_dst}
rsync -a $certs_local_src/{current,$key_dir,$signer} $certs_local_dst/
```
I was going to play around with `rsync` to get it to copy the `certs-local/current` symlink as a symlink & the date folder it points to.

I did have to change the paths slightly in `prepare()` compared to before - I will let you know the changes once the build complete

**Comment by gene-git** [comment]
Okay let me think about the multiple config file question for a bit.
And thanks yes the current_key_dir no longer used and should be removed from docs.

**Comment by gene-git** [comment]
For the sample packge_headers() does this work for you? It uses -L option to copy current and what it refers to not as a link,

      certs_local_src="../../certs-local"
      certs_local_dst="${builddir}/certs-local"

      signer="sign_manual.sh"
      mkdir -p ${certs_local_dst}
      rsync -aL $certs_local_src/current $certs_local_dst/
      rsync -a $certs_local_src/{current,signer} $certs_local_dst/

**Comment by itoffshore** [comment]
A `grep` with `regex` was good enough (there should only ever be one folder in `certs-local` that begins with digits):
```
msg2 "Local Signing certs for out-of-tree modules..."

certs_local_src="../certs-local"
key_dir=$(ls ../certs-local | grep -E "^[0-9]")

certs_local_dst="${builddir}/certs-local"
signer="sign_manual.sh"
mkdir -p ${certs_local_dst}
rsync -a $certs_local_src/{current,$key_dir,$signer} $certs_local_dst/
```
`linux-hardened` just built successfully ;o)

![Screenshot_2022-04-30_22-53-02](https://user-images.githubusercontent.com/1141947/166125199-d39794de-fcdd-494c-826e-13a919747d8c.png)

I'll update my example with all the changed paths (now that `certs-local` lives at the same level as `config`)

**Comment by gene-git** [comment]
Think you're right - it may be helpful to push some of this work down to a script inside certs-local - and simplify the PKGBUILD.
Lert me think about that as well.

**Comment by gene-git** [comment]
In my own upstream kernel git builds - I keep the last N keys - so for me there are actually many such dirs with names beginning with numbers. Certainly safer to do rsync -aL .../current  and that elimitates the need for a link too :)

**Comment by gene-git** [comment]
Great on build completing too :)

**Comment by itoffshore** [comment]
these are the new `PKGBUILD` settings I used with `genkeys.py` on my testing branch (that should probably be reflected in your examples too):

https://github.com/itoffshore/Arch-SKM/blob/alpine/Arch-Linux-PKGBUILD-example

the changes to the paths can be [seen here](https://github.com/itoffshore/Arch-SKM/commit/05773dbb97485787f6ae41b5c34d3eb430eaff14)

**Comment by gene-git** [comment]
Also the dkms stuf which lands in /etc/dkms - should probably be a separate package so it can be installed once and shared across multiple kernels don't you think?

**Comment by gene-git** [comment]
Ah thanks - I'll need to get back to this tomorrow - really appreciate your help and thoughts around improving this - super helpful.

**Comment by gene-git** [comment]
We'll make it even better

**Comment by itoffshore** [comment]
> Also the dkms stuf which lands in /etc/dkms - should probably be a separate package so it can be installed once and shared across multiple kernels don't you think?

`arch-sign-modules` should work for all officially supported kernels - I run it for `linux-hardened` & `linux-lts` & tested it previously with:

- linux
- linux-lts
- linux-hardened
- linux-zen
- linux-hardened-cacule
- linux-xanmod-cacule
- linux-ck
- linux-libre
- AUR kernels (linux-amd & some others)

the `find` regex in my example made it work with the AUR kernels

**Comment by gene-git** [comment]
Ah thats pretty awesome.

**Comment by itoffshore** [comment]
if you want to play around with it the attached `zstd` archive (inside a zip to have github accept it) - has all today's changes

[arch-sign-modules-0.2.65-0-x86_64.pkg.tar.zst.zip](https://github.com/gene-git/Arch-SKM/files/8598048/arch-sign-modules-0.2.65-0-x86_64.pkg.tar.zst.zip)

it may be useful to build some of the obscure AUR kernels to see what they name their `.config`

**Comment by gene-git** [comment]
I pushed some updates - can you take a look and let me know what you think please?

**Comment by itoffshore** [comment]
sure - will try building a few different kernels with the new version

**Comment by gene-git** [comment]
Great thanks - hopefully now that genkeys handles multiple config files it will help resolve current issue okay.

**Comment by itoffshore** [comment]
Hi Gene,

I tested the changes by building:

-  `linux-hardened` 
- `linux-libre` (which has a different `config` for each arch)

the python file globbing expects a path so using:

-  `./genkeys.py -v --config config*` 
-  `./genkeys.py -v --config ../config*` 

fails to generate keys & the build fails in `package_headers()`

* using the [`find` regex](https://github.com/itoffshore/Arch-SKM/blob/d500f62294a60f754a125e1e458229992f6b40eb/Arch-Linux-PKGBUILD-example#L48) in the `PKGBUILD` still works with `genkeys.py`. No harm in leaving this functionality in a shell tool for the time being.

the `config` files we are optionally searching for are:
```
* config.armv7h
* config.i686 
* config.x86_64
```

* I had a think about implementing this in python. Checking the value for `$CARCH` in `/etc/makepkg.conf` is probably the simplest way to find the build system's arch - I don't know if `platform.machine()` gives the same answer on ARM as above ? (so leave this as `TODO`for the moment)

* I've updated `arch-sign-modules` with your latest changes & a working `PKGBUILD` example if you wanted to test your file globbing with some different kernels:

[arch-sign-modules-0.2.65-0-x86_64.pkg.tar.zst.zip](https://github.com/gene-git/Arch-SKM/files/8599586/arch-sign-modules-0.2.65-0-x86_64.pkg.tar.zst.zip)

* as soon as the kernel begins compiling (after the patches are applied) - you can cancel compilation & check `/path/to/makepkg/$kernel/src/certs-local` to see if any certificates are generated.

* here's a [`diff` of the changes](https://github.com/itoffshore/Arch-SKM/commit/d500f62294a60f754a125e1e458229992f6b40eb.diff) I also made to [remove whitespace from the python scripts](https://github.com/itoffshore/Arch-SKM/commit/d500f62294a60f754a125e1e458229992f6b40eb)

* I will build a few more kernels & if all ok make a new release for `arch-sign-modules` next week - unless you wanted to work some more on `genkeys.py` file globbing.

**Comment by gene-git** [comment]
question - did you try quoting the wildcard
./genkeys.py -v --config 'config*'

you can try running at command line to confirm.

**Comment by gene-git** [comment]
So if your dir set up is:
config.1
config.2
...
run by hand 
../certs-local/genkeys.py -v --config 'config.*'

and check the certs-local dir for keys and the configs:
grep CONFIG_SYSTEM_TRUSTED_KEYS config*

**Comment by gene-git** [comment]
i meant ./certs-loccal/genkeys.py 
in PKGBUILD confirm that the paths are right:

e.g. if you're in ./src dir of package build and config is in package dir then it would be
../certs-local/genkeys.py -v --config '../config.*'

But first check by hand then confirm its used correctly by package.

let me know.

thanks.

**Comment by itoffshore** [comment]
yes single quotes solved it ;o)

will build `linux-libre` & `linux-hardened` again as a final check

**Comment by gene-git** [comment]
Ah great - glad that worked. Like it when stuff works :)

**Comment by gene-git** [comment]
Did you switch to use install-certs.py too ?

**Comment by itoffshore** [comment]
yes using `install-certs.py` too [as shown here](https://github.com/itoffshore/Arch-SKM/blob/d500f62294a60f754a125e1e458229992f6b40eb/Arch-Linux-PKGBUILD-example#L93)

I guess without the single quotes the file `glob` interprets `../config*` as multiple arguments when it is expecting a single argument or input that can be interpreted as a single `list` object.

`linux-libre` is building with certificates generated correctly in `prepare()`

**Comment by gene-git** [comment]
Yes in this case we want the code to get the wildcard and not have shell do its thing - really glad its working okay for you.
Its definitely better with your help.

Let me know if there's anything else you think might need tweaking.

**Comment by itoffshore** [comment]
I think that's everything - maybe just add a note in `help` to quote wildcard paths e.g:

`Kernel Config(s) to be updated (../config) - wildcards ok but must be 'quoted'`

**Comment by gene-git** [comment]
good idea done. thank you!
