### ISSUE TITLE
sign_manual.sh - $ext should be zst not zstd

### ISSUE THREAD

**Issue by itoffshore** [gene-git/Arch-SKM#4]
I noticed this merging the changes - I think this extension check should be `zst` not `zstd` (I've been using `zst` [since last August](https://github.com/itoffshore/Arch-SKM/commit/3fc871ff12fc26e48804280e1a2499da5b1f9dd9))

https://github.com/gene-git/Arch-SKM/blob/250c615b32991e97e1b03e9a1e32fd90a6a51590/certs-local/sign_manual.sh#L94

unless you name your modules `.zstd` in which case add an `||` condition

---

I also[ added functionality for `gz`](https://github.com/itoffshore/Arch-SKM/blob/4c2de490b3870f11bb2097095fe77a3b1e40bd76/certs-local/sign_manual.sh#L99) compressed modules (some AUR kernel or another still uses it - it's why I added the ability in `arch-sign-modules` to change the module compression)

**Comment by itoffshore** [comment]
I've made the change to my `master` - I'm going to rebuild `linux-hardened` & double check the signatures.

If it's all OK I'll make a PR to fix this & also merge the whitespace fixes back to you.

**Comment by gene-git** [comment]
Yes very good point - thanks for pointing that out.  I took your changes thank you. 
Note that dkms doesn't use the manual signing script - its there for human convenience.
I also added gzip support to the dkms signer - it is simpler as doesn't need to deal with already signed modules.

Let me know if okay now.

Thanks again!

**Comment by itoffshore** [comment]
I also found a small type with `hexdump` (`--e` instead of `-e`)

https://github.com/itoffshore/Arch-SKM/commit/bae795c1c7d2b080726e46a080268f76b270624a

**Comment by gene-git** [comment]
Geez,  I thought I fixed that - guess not.
Now fixed.
thank you - again!

**Comment by itoffshore** [comment]
last typo I think:

https://github.com/gene-git/Arch-SKM/blob/aedc3c61f86c950a8438be7db34bec28dc4be494/certs-local/dkms/kernel-sign.sh#L60

(should be `compress gz`)

**Comment by gene-git** [comment]
Yep - thank you - fixed

**Comment by gene-git** [comment]
Thank you for all your work - very much appreciated

**Comment by itoffshore** [comment]
no problem - 2 eyes are better than one ;o)

**Comment by gene-git** [comment]
Super helpful. Hopefully we're at a reasonably good place now.

**Comment by itoffshore** [comment]
I was just going to do a final `diff` to see if we can sync `certs-local` - I have a few whitespace fixes you could also apply (in `nano` they show up as green blocks)

**Comment by itoffshore** [comment]
these are the final differences between our `certs-local`: 

[whitespace.patch.zip](https://github.com/gene-git/Arch-SKM/files/8604132/whitespace.patch.zip)

* I remove a comment `#SIGN=$kernel_source_dir/certs-local/sign_manual.sh` from `dkms/kernel-sign.sh`
* & use `xz -f $modunc` in `sign_manual.sh`
* the other 95% are whitespace fixes

---

To apply the changes:

```
cd Arch-SKM
git checkout -b testing
cd ../
```
with `whitespace.patch` at the same folder level as `Arch-SKM` 

`patch -p 0 --dry-run < whitespace.patch` (should apply cleanly in theory)

if all ok apply the patch & commit the changes to a new remote testing branch:
```
patch -p 0 < whitespace.patch
cd Arch-SKM
git add .
git commit
git push -u origin testing
```

You can then make a `PR` to yourself & see the merge changes a bit more easily than you can with a `diff`

**Comment by itoffshore** [comment]
I'm going to setup a new `arch-sign-modules` repo with `Arch-SKM` within in it as a submodule to make it easier to keep our changes in sync (so I can make a `PR` for the above changes)

**Comment by gene-git** [comment]
Thank you  - looks good to me - patch set applied and pushed back here.

**Comment by itoffshore** [comment]
`submodules` don't seem to work that well with repos that are not forks for generating a `PR` (or I need to do some more reading)

I noticed a small typo:
https://github.com/gene-git/Arch-SKM/blob/358fbaf07a27f9acd26d41c9ae585c2199a61200/README.md?plain=1#L257

s/be also (not alos)

**Comment by gene-git** [comment]
indeed. you ok with the wording there or want to maybe add/tweak - maybe say a few words

**Comment by itoffshore** [comment]
maybe add:
```
arch-sign-modules reduces the manual steps for building a fully signed custom kernel to 3 commands to *Update* / *Build* & *Install* the kernel:

abk -u kernel-name
abk -b kernel-name
abk -i kernel-name

* [README.scripts.md](https://github.com/itoffshore/Arch-SKM/blob/master/README.scripts.md)

* [PKGBUILD example](https://github.com/itoffshore/Arch-SKM/blob/master/Arch-Linux-PKGBUILD-example)
```

**Comment by gene-git** [comment]
Done

**Comment by gene-git** [comment]
If you're good with this - i'll re-tag and push another release - thank you again for all your efforts improving and testing.

**Comment by itoffshore** [comment]
yes no problem I think we ironed out everything

thanks for your efforts too - you can never have too much security ;o)

I'm pushing the new `arch-sign-modules` to AUR shortly

**Comment by gene-git** [comment]
Agree completely on security. Thank you agian.
