### ISSUE TITLE
Much faster kernel module signer

### ISSUE THREAD

**Issue by ntninja** [gene-git/Arch-SKM#6]
Hi! I wrote a much faster kernel module signer than what calling `sign-file` in a loop can achieve. It’s available here: https://gitlab.com/ntninja/sign-modules-fast/

Thought you might be interested in this?

**Comment by gene-git** [comment]
Interesting will take a look - thanks! 
Though there are only a few out of tree kernel modules signed in typical usage so speed not critical for this use case I would think.

Thanks for sharing!

**Comment by gene-git** [comment]
I plan to stay with the kernel signing tool - thanks again for sharing.
